### ISSUE TITLE
Quests sometimes do not correctly recognize already completed quest steps

### ISSUE THREAD

**Issue by ZapZockt** [WarpzoneStudios/Hammerting#77]
**Describe the bug**
As example: 
The Quest "Das Erste Gießen" (German, in English maybe "The first smelting") is not recognizing, that the 4 bars, that were asked are already done. I had similar bugs with other quests, like as a different example "find 3 rat holes" and the quest stood at 2/3 although I had 4+ already taken down. Often these quests get marked as completed later when the 5th rat hole or the 25th copper bar is reached, but it is not expected behavior of the quest to not complete if the goal is reached at first.

As you can see in the screenshot below, my dwarfs have smelted more than 4 bars already, but the quest is stuck at 3/4 (see bottom right corner of the screen):

**To Reproduce**
Start a new game, wait for the quest to start, smelt bars, observe if it is finished after 4 bars or not. I assume this is not a persistent error, as I started the game dozens of times, and it mostly ended correctly. Similar things happen with other quests from time to time, so it might be a general problem in the process of how the recognition of quest goals is done.

**Expected behavior**
The quest should be marked as fulfilled after the first 4 bars are smelted

**Screenshots**
![grafik](https://user-images.githubusercontent.com/78972579/109773313-5a7dc180-7bff-11eb-96d6-e94603b9c61d.png)

**Comment by ZapZockt** [comment]
As an additional hint: 
The quest from the example above was immediately marked as completed, after I did a savegame, reloaded, and crafted another bar.

**Comment by Srekel** [comment]
Fixed in 0.2.1.0 (I hope, please keep an eye out for it!)

**Comment by ZapZockt** [comment]
unfortunately not solved:

![grafik](https://user-images.githubusercontent.com/78972579/110215854-398dc880-7eac-11eb-98cb-71d914462646.png)

Rathole 0/3 and you can see the dwarf in front of the rathole.

**Comment by Srekel** [comment]
Was this perhaps from a save before this version?

Would you mind providing a save game from before you unlocked the event, or before you discovered the rathole?

**Comment by ZapZockt** [comment]
Nope, completely new game started after doing the last update. I always play with the latest experimental and I try to start a new game with almost every version, unless there are several per week in a quick order.

**Comment by ZapZockt** [comment]
Update: 
- started a new game again with 0.2.1.6
- got the rathole quest
- played to the point, where I found the first rathole
- rathole was not detected
- made a savegame at the moment, the rathole was found and attached the last autosave before the rathole was found too
- hope this helps to find the bug

[rathole-not-detected.zip](https://github.com/WarpzoneStudios/Hammerting/files/6136059/rathole-not-detected.zip)
